version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ../laravel/:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: laravel-web
    working_dir: /var/www
    volumes:
      - ../laravel:/var/www
    ports:
      - 8080:80
  db:
    image: mariadb:latest
    container_name: laravel-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

volumes:
  dbdata: